export { default as HomeLayout } from './HomeLayout' 
export { default as Landing } from './Landing' 
export { default as Skills } from './Skills' 
export { default as About } from './About' 
export { default as Projects } from './Projects' 
export { default as Error } from './Error' 
export { default as Contact } from './Contact' 